apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    component: grafana
data:
  prometheus-datasource.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
    - name: Graphite
      orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-web:80
      basicAuth: false
      isDefault: true
      version: 1
      editable: false

  # dynamic dashboard creation
  loki-datasource.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
    - name: Graphite
      orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
